#!/usr/bin/env python3
"""Generates Nagmo's minimalist mascot (a little sticky note) from one shape
definition, as:
  * SVGs in branding/
  * Android vector drawables (widgets, launcher icon, notifications)
  * MascotArt.kt, so the in-app mascot can be drawn in the user's accent colour

Run from the repo root:  python3 branding/generate_art.py
"""
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SVG_DIR = os.path.join(ROOT, "branding")
DRAWABLE_DIR = os.path.join(ROOT, "app", "src", "main", "res", "drawable")
KOTLIN_FILE = os.path.join(ROOT, "app", "src", "main", "java", "com", "nagmo", "app", "ui", "components", "MascotArt.kt")

# Brand colours (used for static art; in-app the body follows the accent).
BODY = "#FFD66B"
FOLD = "#F2B937"
INK = "#26221C"
BLUSH = "#FF7A8A"

# Roles: body, fold, ink (face), blush, mark (symbols outside the note). Each shape: (role, kind, d, stroke_width)
BODY_PATH = "M32,14 H68 Q86,14 86,32 V66 L66,86 H32 Q14,86 14,68 V32 Q14,14 32,14 Z"
FOLD_PATH = "M86,66 L73,66 Q66,66 66,73 L66,86 Z"


def ellipse(cx, cy, rx, ry):
    return (f"M{cx - rx:g},{cy:g} a{rx:g},{ry:g} 0 1,0 {2 * rx:g},0 "
            f"a{rx:g},{ry:g} 0 1,0 {-2 * rx:g},0 Z")


def circle(cx, cy, r):
    return ellipse(cx, cy, r, r)


def fill(role, d):
    return (role, "fill", d, 0)


def stroke(role, d, w):
    return (role, "stroke", d, w)


def base():
    return [fill("body", BODY_PATH), fill("fold", FOLD_PATH),
            fill("blush", ellipse(29, 59, 5, 3)), fill("blush", ellipse(71, 59, 5, 3))]


def dot_eyes():
    return [fill("ink", circle(38, 50, 3.6)), fill("ink", circle(62, 50, 3.6))]


MASCOTS = {
    "happy": base() + dot_eyes() + [stroke("ink", "M45,59 Q50,64 55,59", 3)],
    "nagging": base() + dot_eyes() + [
        stroke("ink", "M32,41 L41,43.5", 2.8), stroke("ink", "M68,41 L59,43.5", 2.8),
        fill("ink", ellipse(50, 61, 3.2, 3.6)),
        stroke("mark", "M94,4 V13", 3), fill("mark", circle(94, 19.5, 1.8)),
    ],
    "sleepy": base() + [
        stroke("ink", "M34,50 Q38,54 42,50", 2.8), stroke("ink", "M58,50 Q62,54 66,50", 2.8),
        stroke("ink", "M47,61 H53", 2.8),
        stroke("mark", "M85,3 H93 L85,11 H93", 2.4),
    ],
    "party": base() + [
        stroke("ink", "M34,52 L38,47 L42,52", 2.8), stroke("ink", "M58,52 L62,47 L66,52", 2.8),
        fill("ink", "M43,57.5 Q50,68 57,57.5 Z"),
        fill("fold", "M92,2 Q93,8 98,9 Q93,10 92,16 Q91,10 86,9 Q91,8 92,2 Z"),
    ],
}

COLORS = {"body": BODY, "fold": FOLD, "ink": INK, "blush": BLUSH, "mark": INK}
ALPHA = {"blush": 0.45}


def svg(shapes, background=None):
    out = ['<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" width="400" height="400">']
    if background:
        out.append(background)
    for role, kind, d, w in shapes:
        a = ALPHA.get(role)
        op = f' opacity="{a}"' if a else ""
        if kind == "fill":
            out.append(f'  <path d="{d}" fill="{COLORS[role]}"{op}/>')
        else:
            out.append(f'  <path d="{d}" fill="none" stroke="{COLORS[role]}" stroke-width="{w}" '
                       f'stroke-linecap="round" stroke-linejoin="round"{op}/>')
    out.append("</svg>")
    return "\n".join(out) + "\n"


def vector_paths(shapes, indent):
    out = []
    for role, kind, d, w in shapes:
        attrs = [f'android:pathData="{d}"']
        a = ALPHA.get(role)
        if kind == "fill":
            attrs.append(f'android:fillColor="{COLORS[role]}"')
            if a:
                attrs.append(f'android:fillAlpha="{a}"')
        else:
            attrs += [f'android:strokeColor="{COLORS[role]}"', f'android:strokeWidth="{w}"',
                      'android:strokeLineCap="round"', 'android:strokeLineJoin="round"']
        out.append(f"{indent}<path\n{indent}    " + f"\n{indent}    ".join(attrs) + " />")
    return "\n".join(out)


def vector(shapes, dp, viewport, group=None, background=None):
    body = vector_paths(shapes, "        " if group else "    ")
    if group:
        body = f"    <group {group}>\n{body}\n    </group>"
    bg = ""
    if background:
        bg = (f'    <path\n        android:fillColor="{background}"\n'
              f'        android:pathData="M0,0h{viewport}v{viewport}h-{viewport}z" />\n')
    return ('<?xml version="1.0" encoding="utf-8"?>\n'
            '<!-- Generated by branding/generate_art.py. Do not edit by hand. -->\n'
            '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
            f'    android:width="{dp}dp"\n    android:height="{dp}dp"\n'
            f'    android:viewportWidth="{viewport}"\n    android:viewportHeight="{viewport}">\n'
            f"{bg}{body}\n</vector>\n")


def write(path, text):
    with open(path, "w") as f:
        f.write(text)


def kotlin():
    lines = [
        "// Generated by branding/generate_art.py. Do not edit by hand.",
        "package com.nagmo.app.ui.components",
        "",
        "/** MARK = little symbols floating outside the note (\"!\", \"z\"). */",
        "internal enum class Part { BODY, FOLD, INK, BLUSH, MARK }",
        "",
        "/** One shape of the mascot, in a 100x100 viewport. strokeWidth 0 = filled. */",
        "internal class MascotShape(val part: Part, val pathData: String, val strokeWidth: Float)",
        "",
        "internal object MascotArt {",
    ]
    for name, shapes in MASCOTS.items():
        lines.append(f"    val {name} = listOf(")
        for role, kind, d, w in shapes:
            lines.append(f'        MascotShape(Part.{role.upper()}, "{d}", {float(w)}f),')
        lines.append("    )")
    lines.append("}")
    return "\n".join(lines) + "\n"


def main():
    for f in os.listdir(SVG_DIR):
        if f.endswith(".svg"):
            os.remove(os.path.join(SVG_DIR, f))
    for name, shapes in MASCOTS.items():
        write(os.path.join(SVG_DIR, f"mascot_{name}.svg"), svg(shapes))
        write(os.path.join(DRAWABLE_DIR, f"mascot_{name}.xml"), vector(shapes, 120, 100))
    write(KOTLIN_FILE, kotlin())

    # Launcher icon: the happy note centred in the 66dp safe zone of a 108dp canvas.
    scale = 0.62
    offset = (108 - 100 * scale) / 2
    group = (f'android:scaleX="{scale}" android:scaleY="{scale}" '
             f'android:translateX="{offset:g}" android:translateY="{offset + 1:g}"')
    write(os.path.join(DRAWABLE_DIR, "ic_launcher_foreground.xml"),
          vector(MASCOTS["happy"], 108, 108, group=group))

    # Monochrome (themed icon) and notification icon: silhouette with face cut out.
    silhouette = " ".join([BODY_PATH, circle(38, 50, 3.6), circle(62, 50, 3.6),
                           "M44,58 Q50,66 56,58 Q50,61 44,58 Z"])
    mono = ('<?xml version="1.0" encoding="utf-8"?>\n'
            '<!-- Generated by branding/generate_art.py. Do not edit by hand. -->\n'
            '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
            '    android:width="{dp}dp"\n    android:height="{dp}dp"\n'
            '    android:viewportWidth="{vp}"\n    android:viewportHeight="{vp}"{tint}>\n'
            '    <group {group}>\n'
            '        <path\n'
            '            android:fillType="evenOdd"\n'
            '            android:fillColor="#FFFFFFFF"\n'
            f'            android:pathData="{silhouette}" />\n'
            '    </group>\n</vector>\n')
    write(os.path.join(DRAWABLE_DIR, "ic_launcher_monochrome.xml"),
          mono.format(dp=108, vp=108, tint="", group=group))
    small = 'android:scaleX="0.26" android:scaleY="0.26" android:translateX="-1" android:translateY="-1"'
    write(os.path.join(DRAWABLE_DIR, "ic_stat_nagmo.xml"),
          mono.format(dp=24, vp=24, tint='\n    android:tint="?android:attr/colorControlNormal"', group=small))

    # README logo: the note on the charcoal icon background.
    bg = '<rect x="0" y="0" width="100" height="100" rx="24" fill="#1C1B1F"/>'
    shapes = [(r, k, d, w) for r, k, d, w in MASCOTS["happy"]]
    logo = svg(shapes, background=bg).replace('<path', '<g transform="translate(14 15) scale(0.72)"><path', 1)
    logo = logo.replace("</svg>", "</g></svg>")
    write(os.path.join(SVG_DIR, "logo.svg"), logo)


if __name__ == "__main__":
    main()
