// Generated by branding/generate_art.py. Do not edit by hand.
package com.nagmo.app.ui.components

/** MARK = little symbols floating outside the note ("!", "z"). */
internal enum class Part { BODY, FOLD, INK, BLUSH, MARK }

/** One shape of the mascot, in a 100x100 viewport. strokeWidth 0 = filled. */
internal class MascotShape(val part: Part, val pathData: String, val strokeWidth: Float)

internal object MascotArt {
    val happy = listOf(
        MascotShape(Part.BODY, "M32,14 H68 Q86,14 86,32 V66 L66,86 H32 Q14,86 14,68 V32 Q14,14 32,14 Z", 0.0f),
        MascotShape(Part.FOLD, "M86,66 L73,66 Q66,66 66,73 L66,86 Z", 0.0f),
        MascotShape(Part.BLUSH, "M24,59 a5,3 0 1,0 10,0 a5,3 0 1,0 -10,0 Z", 0.0f),
        MascotShape(Part.BLUSH, "M66,59 a5,3 0 1,0 10,0 a5,3 0 1,0 -10,0 Z", 0.0f),
        MascotShape(Part.INK, "M34.4,50 a3.6,3.6 0 1,0 7.2,0 a3.6,3.6 0 1,0 -7.2,0 Z", 0.0f),
        MascotShape(Part.INK, "M58.4,50 a3.6,3.6 0 1,0 7.2,0 a3.6,3.6 0 1,0 -7.2,0 Z", 0.0f),
        MascotShape(Part.INK, "M45,59 Q50,64 55,59", 3.0f),
    )
    val nagging = listOf(
        MascotShape(Part.BODY, "M32,14 H68 Q86,14 86,32 V66 L66,86 H32 Q14,86 14,68 V32 Q14,14 32,14 Z", 0.0f),
        MascotShape(Part.FOLD, "M86,66 L73,66 Q66,66 66,73 L66,86 Z", 0.0f),
        MascotShape(Part.BLUSH, "M24,59 a5,3 0 1,0 10,0 a5,3 0 1,0 -10,0 Z", 0.0f),
        MascotShape(Part.BLUSH, "M66,59 a5,3 0 1,0 10,0 a5,3 0 1,0 -10,0 Z", 0.0f),
        MascotShape(Part.INK, "M34.4,50 a3.6,3.6 0 1,0 7.2,0 a3.6,3.6 0 1,0 -7.2,0 Z", 0.0f),
        MascotShape(Part.INK, "M58.4,50 a3.6,3.6 0 1,0 7.2,0 a3.6,3.6 0 1,0 -7.2,0 Z", 0.0f),
        MascotShape(Part.INK, "M32,41 L41,43.5", 2.8f),
        MascotShape(Part.INK, "M68,41 L59,43.5", 2.8f),
        MascotShape(Part.INK, "M46.8,61 a3.2,3.6 0 1,0 6.4,0 a3.2,3.6 0 1,0 -6.4,0 Z", 0.0f),
        MascotShape(Part.MARK, "M94,4 V13", 3.0f),
        MascotShape(Part.MARK, "M92.2,19.5 a1.8,1.8 0 1,0 3.6,0 a1.8,1.8 0 1,0 -3.6,0 Z", 0.0f),
    )
    val sleepy = listOf(
        MascotShape(Part.BODY, "M32,14 H68 Q86,14 86,32 V66 L66,86 H32 Q14,86 14,68 V32 Q14,14 32,14 Z", 0.0f),
        MascotShape(Part.FOLD, "M86,66 L73,66 Q66,66 66,73 L66,86 Z", 0.0f),
        MascotShape(Part.BLUSH, "M24,59 a5,3 0 1,0 10,0 a5,3 0 1,0 -10,0 Z", 0.0f),
        MascotShape(Part.BLUSH, "M66,59 a5,3 0 1,0 10,0 a5,3 0 1,0 -10,0 Z", 0.0f),
        MascotShape(Part.INK, "M34,50 Q38,54 42,50", 2.8f),
        MascotShape(Part.INK, "M58,50 Q62,54 66,50", 2.8f),
        MascotShape(Part.INK, "M47,61 H53", 2.8f),
        MascotShape(Part.MARK, "M85,3 H93 L85,11 H93", 2.4f),
    )
    val party = listOf(
        MascotShape(Part.BODY, "M32,14 H68 Q86,14 86,32 V66 L66,86 H32 Q14,86 14,68 V32 Q14,14 32,14 Z", 0.0f),
        MascotShape(Part.FOLD, "M86,66 L73,66 Q66,66 66,73 L66,86 Z", 0.0f),
        MascotShape(Part.BLUSH, "M24,59 a5,3 0 1,0 10,0 a5,3 0 1,0 -10,0 Z", 0.0f),
        MascotShape(Part.BLUSH, "M66,59 a5,3 0 1,0 10,0 a5,3 0 1,0 -10,0 Z", 0.0f),
        MascotShape(Part.INK, "M34,52 L38,47 L42,52", 2.8f),
        MascotShape(Part.INK, "M58,52 L62,47 L66,52", 2.8f),
        MascotShape(Part.INK, "M43,57.5 Q50,68 57,57.5 Z", 0.0f),
        MascotShape(Part.FOLD, "M92,2 Q93,8 98,9 Q93,10 92,16 Q91,10 86,9 Q91,8 92,2 Z", 0.0f),
    )
}
